ARM: tegra: loki: fix build error due to warning
Fix following build error:
****
board-loki-sensors.c: In function 'loki_mt9m114_power_on':
board-loki-sensors.c:118:2: error: implicit declaration of function 'regulator_enable' [-Werror=implicit-function-declaration]
board-loki-sensors.c:135:2: error: implicit declaration of function 'regulator_disable' [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
****

Change-Id: I4a624522031d1f9a6af2f1421320cda6789544c1
Signed-off-by: Laxman Dewangan <ldewangan@nvidia.com>
Reviewed-on: http://git-master/r/276580