Include required header file
Insert missing include file, felt
when CONFIG_COMPAT=n

drivers/devfreq/governor_wmark_active.c:
In function 'devfreq_watermark_target_freq':
drivers/devfreq/governor_wmark_active.c:146:25:
error: implicit declaration of function
'ktime_get' [-Werror=implicit-function-declaration]
ktime_t current_time = ktime_get();

drivers/devfreq/governor_wmark_active.c:146:25:
error: invalid initializer

Bug 200187768

Change-Id: I0b2deda3cbbc9b2af5c4846e0a20614eadb04353
Signed-off-by: Joe Korty <joe.korty@ccur.com>
Signed-off-by: Gaurav Singh <gaursingh@nvidia.com>
Reviewed-on: http://git-master/r/1163926
GVS: Gerrit_Virtual_Submit
Reviewed-by: Bibek Basu <bbasu@nvidia.com>