ARM: tegra: config: disable TRACEDUMP for ardbeg MODS
Both CONFIG_TRACEDUMP and CONFIG_TRACEDUMP_PROCFS are disabled
since they give build error on kernel 3.10

kernel/kernel/trace/tracedump.c: In function 'iter_init':
kernel/kernel/trace/tracedump.c:155:3: error: 'struct trace_array' has no member named 'data'
kernel/kernel/trace/tracedump.c:167:36: error: 'struct trace_array' has no member named 'buffer'
kernel/kernel/trace/tracedump.c: In function 'iter_deinit':
kernel/kernel/trace/tracedump.c:209:3: error: 'struct trace_array' has no member named 'data'
kernel/kernel/trace/tracedump.c: In function 'pager_init':
kernel/kernel/trace/tracedump.c:227:3: error: 'struct trace_array' has no member named 'data'
kernel/kernel/trace/tracedump.c: In function 'pager_next':
kernel/kernel/trace/tracedump.c:261:53: error: 'struct trace_array' has no member named 'buffer'
kernel/kernel/trace/tracedump.c:267:38: error: 'struct trace_array' has no member named 'buffer'
kernel/kernel/trace/tracedump.c: In function 'pager_deinit':
kernel/kernel/trace/tracedump.c:281:38: error: 'struct trace_array' has no member named 'buffer'
kernel/kernel/trace/tracedump.c:284:3: error: 'struct trace_array' has no member named 'data'
kernel/kernel/trace/tracedump.c: In function 'consume_events':
kernel/kernel/trace/tracedump.c:320:30: error: 'struct trace_array' has no member named 'buffer'
kernel/kernel/trace/tracedump.c: In function 'tracedump_initcall':
kernel/kernel/trace/tracedump.c:667:2: error: implicit declaration of function 'create_proc_entry' [-Werror=implicit-function-declaration]
kernel/kernel/trace/tracedump.c:667:8: warning: assignment makes pointer from integer without a cast [enabled by default]
kernel/kernel/trace/tracedump.c:671:8: error: dereferencing pointer to incomplete type
cc1: some warnings being treated as errors

Once these errors are resolved, we can re-enable the config.

Bug 1385705

Change-Id: I7f9224ff21fc0541a88d910b981902640dcc6fad
Signed-off-by: Bharat Nihalani <bnihalani@nvidia.com>
Reviewed-on: http://git-master/r/284353
Reviewed-by: Automatic_Commit_Validation_User
Reviewed-by: Dan Willemsen <dwillemsen@nvidia.com>
Tested-by: Sridhar Lavu <slavu@nvidia.com>