ARM: tegra: usb: fix compile error with modular build
Fixes below error while building xusb as module.
ERROR: "utmi_phy_iddq_override" [drivers/usb/host/xhci-hcd.ko] undefined!

Change-Id: Ice1a8ab21f0e16ab8a663c53c47bf5c8388f7f4a
Signed-off-by: Ajay Gupta <ajayg@nvidia.com>
Reviewed-on: http://git-master/r/218605
Reviewed-by: Jui Chang Kuo <jckuo@nvidia.com>
Reviewed-by: Ashutosh Jha <ajha@nvidia.com>
(cherry picked from commit bd4bec18bef236d729e9498d6830512f3bfeb521)
Reviewed-on: http://git-master/r/221211
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit