Include the required header file
Insert missing #include file, felt
when CONFIG_COMPAT=n.

drivers/firmware/tegra/bpmp.c:
In function 'bpmp_ping_show':
drivers/firmware/tegra/bpmp.c:465:7: error:
implicit declaration of
function 'ktime_get' [-Werror=implicit-function-declaration]
tm = ktime_get();

drivers/firmware/tegra/bpmp.c:465:5: error:
incompatible types when assigning to type 'ktime_t
{aka union ktime}' from type 'int'
tm = ktime_get();

include/linux/ktime.h:85:30: error: request for member
'tv64' in something not a structure or union
({ (ktime_t){ .tv64 = (lhs).tv64 - (rhs).tv64 }; })
                              ^
drivers/firmware/tegra/bpmp.c:468:7: note: in expansion
of macro 'ktime_sub'
tm = ktime_sub(ktime_get(), tm);

Bug 200187768

Change-Id: I4c355276560971eb98ab1ffa87713e665d857457
Signed-off-by: Joe Korty <joe.korty@ccur.com>
Signed-off-by: Gaurav Singh <gaursingh@nvidia.com>
Reviewed-on: http://git-master/r/1163925
GVS: Gerrit_Virtual_Submit
Reviewed-by: Bibek Basu <bbasu@nvidia.com>