power: sbs: fix compilation error
Fix compilation error:
/**
sbs-battery.c:959:8: warning: initialization from incompatible pointer type [enabled by default]
sbs-battery.c:959:8: warning: (near initialization for 'sbs_pm_ops.resume') [enabled by default]
sbs-battery.c:959:8: warning: initialization from incompatible pointer type [enabled by default]
sbs-battery.c:959:8: warning: (near initialization for 'sbs_pm_ops.thaw') [enabled by default]
sbs-battery.c:959:8: warning: initialization from incompatible pointer type [enabled by default]
sbs-battery.c:959:8: warning: (near initialization for 'sbs_pm_ops.restore') [enabled by default]
*/

Change-Id: I1afccaec7337762d4cf376c58bed9c3f4f7e47a4
Signed-off-by: Laxman Dewangan <ldewangan@nvidia.com>
Reviewed-on: http://git-master/r/360086
(cherry picked from commit 2ec66177fd788a21da73cc2b98373781eab1fe06)

Signed-off-by: Laxman Dewangan <ldewangan@nvidia.com>
Change-Id: I4f9746dc05216fed337cc062060019fe84d45a5b
Reviewed-on: http://git-master/r/362840