ARM64: fix build issue when supporting 64K pages
CONFIG_COMPAT is disabled when CONFI_ARM64_64K_PAGES is enabled.
Hence, the following compilation error

arch/arm64/kernel/built-in.o: In function `el0_sync':
.../arch/arm64/kernel/entry.S:358: undefined reference to `el0_sync_tramp'

Fix it by removing CONFIG_COMPAT protection for el0_sync_tramp and
ret_from_exception so that the branch prediction optimization
stays for both 4K and 64K pages.

Bug 1526131

Change-Id: I1531809df536d6d93b6732b9dc1c28893eb1200e
Signed-off-by: Sri Krishna chowdary <schowdary@nvidia.com>
Reviewed-on: http://git-master/r/454023
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>