power: charger-gauge-comm: fix compilation error
Fix compilation error:
/**
battery-charger-gauge-comm.c: In function 'battery_charger_thermal_monitor_wq':
battery-charger-gauge-comm.c:104:28: warning: unused variable 'node' [-Wunused-variable]
**/
Signed-off-by: Laxman Dewangan <ldewangan@nvidia.com>

Change-Id: I34a281c50586281bd0487e1d4ce3ea9dc445a851
Reviewed-on: http://git-master/r/360085
(cherry picked from commit e771bb94cc832e0939f3afc09a667cf20048c05c)

Signed-off-by: Laxman Dewangan <ldewangan@nvidia.com>
Change-Id: I818ce1e136320aa1d8586b7167d41e8a3e5fd6cb
Reviewed-on: http://git-master/r/362839